### ISSUE TITLE
Perform "make clean" to make source code global to all computers

### ISSUE THREAD

**Issue by mysterypaint** [MegaPramuk/HCL-3DS#1]
Hello! I was taking a peek at this source code (thank you for hosting it) and I noticed I couldn't compile because the objects that were already in the /build/ folder were pointing to a different computer's install directory. Can you update the master branch by performing "make clean" in the terminal to make the source code global to all computers?

Thanks for your time!

**Comment by MegaPramuk** [comment]
Huh, didn't think that someone might find this repo actually, especially after such a long time.
I didn't even notice that as I simply hosted the files as they were, but it's fixed now.
Thanks for telling me!
